Ext.define("core.bl.order.controller.OrderContentController",{
	extend:"Ext.app.Controller",
	init:function(){
		var self=this
		//事件注册
		this.control({
		});
	},
	views:[
	"core.bl.order.view.OrderContentGrid",
	"core.bl.order.view.OrderContentPanel",
	"core.bl.order.view.OrderContentForm",
	"core.bl.order.view.OrderItemGrid",
	"core.bl.order.view.OrderItemPanel",
	"core.bl.order.view.OrderItemForm"
	],
	stores:[
	        "core.bl.order.store.OrderContentStore",
	        "core.bl.order.store.OrderItemStore"
		]
});