Ext.define("core.bl.ren.view.RentalImgPanel",{
	extend:"core.app.base.BasePanel",
	alias:"widget.bl.rentalImgPanel",
	funCode:"rentalImg_main",
	funData:{
	        action:"/bl/renimg", //请求Action
	        whereSql:"",//表格查询条件
	        orderSql:"operatingTime",//表格排序条件
	        pkName:"imgid",
	        modelName:"org.yingqu.baoli.model.RentalImg",//实体全路径
	        tableName:"RentalImg",//表名
	        isChildren:true,//是否子功能
	        parentCode:"rental_main",//主功能功能编码
	        connectFields:[{//关联字段
			mainFieldCode:"rid",//主功能字段名
			childFieldCode:"rental",//子功能字段名
			foreignKey:"foreignKey",//外键虚字段
			isQuery:true
			}]
	},
		items:{
			xtype:"bl.rentalImgGrid",
			region:"center"
		}
});
