Ext.define("core.bl.sell.view.RentalPanel",{
	extend:"core.app.base.BasePanel",
	alias:"widget.bl.sellPanel",
	funCode:"rental_main",
	funData:{
	        action:"/bl/sell", //请求Action
	        whereSql:"",//表格查询条件
	        orderSql:"operatingTime",//表格排序条件
	        pkName:"rid",
	        modelName:"org.yingqu.baoli.model.Rental",//实体全路径
	        tableName:"Rental",//表名
	        isChildren:false,//是否子功能
	        children:[{//子功能的配置
	        	funCode:"rentalImg_main"	        	
			}]
	},
		items:[{
		xtype:"basecenterpanel",
				items:[{
					xtype:"basequerypanel",
					region:"north",
					items:[
			  {
				xtype:"basequeryfield",
				queryType:"textfield",
				fieldLabel:"发布时间",
				name:"ptime",
				config:{
				}
			},
			  {
				xtype:"basequeryfield",
				queryType:"textfield",
				fieldLabel:"发布状态",
				name:"state",
				config:{
				}
			},
			]
			},{
			xtype:"bl.sellGrid",
			region:"center"
		}]
	},{
	xtype:"bl.sellForm",
		hidden:true
	}]
});
