Ext.define("core.bl.adt.view.AdvertisementPanel",{
	extend:"core.app.base.BasePanel",
	alias:"widget.bl.advertisementPanel",
	funCode:"advertisement_main",
	funData:{
	        action:"/bl/adt", //请求Action
	        whereSql:"",//表格查询条件
	        orderSql:"operatingTime",//表格排序条件
	        pkName:"adverid",
	        modelName:"org.yingqu.baoli.model.Advertisement",//实体全路径
	        tableName:"Advertisement",//表名
	        defaultObj:{enabled:"1"},//默认信息，用于表格添加的时候字段默认值
	        isChildren:false,//是否子功能
	        children:[{//子功能的配置
	        	funCode:"avvertiseImageUrl_main"	        	
	        }]
	},
		items:[{
		xtype:"basecenterpanel",
				items:[{
					xtype:"basequerypanel",
					region:"north",
					items:[
			  {
				xtype:"basequeryfield",
				queryType:"textfield",
				fieldLabel:"内容",
				name:"msg",
				config:{
				}
			},
			  {
				xtype:"basequeryfield",
				queryType:"basecombobox",
				fieldLabel:"投放状态",
				name:"ispost",
				config:{
					ddCode:"TSTATE"
				}
			},
			]
			},{
			xtype:"bl.advertisementGrid",
			region:"center"
		}]
	},{
	xtype:"bl.advertisementForm",
		hidden:true
	}]
});
