Ext.define("core.rbac.user.view.UserGrid",{
	extend:"core.app.base.BaseGrid",
	alias:"widget.rbac.usergrid",
	tbar:[
		{xtype:'button',text:'添加',ref:'gridInsert',iconCls:'table_add'},
		{xtype:'button',text:'删除',ref:'gridDelete',iconCls:'table_remove'},
		{xtype:'button',text:'保存',ref:'gridSave',iconCls:'table_save'}
	],
	columns:[{
		xtype:"rownumberer",
		width : 35,
		text :'No.',
		align : 'center'
	},{
		text:"主键",
		dataIndex:"userId",
		hidden:true
	},{
		text:"姓名",
		dataIndex:"username",
		field:{
			xtype:"textfield"
		}
	},{
		text:"编码",
		dataIndex:"userCode",
		field:{
			xtype:"textfield"
		}		
	},{
		text:"性别",
		dataIndex:"sex",
		columnType:"basecombobox",
		ddCode:"SEX",
		field:{
			xtype:"basecombobox",
			ddCode:"SEX"
		}
	},{
		text:"创建日期",
		dataIndex:"createTime",
		width:150,
		field:{
			xtype:"datetimefield",
			dateType:"date"
		}
	}],
	store:"core.rbac.user.store.UserStore",
	bbar:{
		xtype:'pagingtoolbar',
		store:'core.rbac.user.store.UserStore',
		dock:'bottom',
		displayInfo:true
	}
});