Ext.define("core.bl.mc.view.MerchantPanel",{
	extend:"core.app.base.BasePanel",
	alias:"widget.bl.merchantPanel",
	funCode:"merchant_main",
	funData:{
	        action:"/bl/mc", //请求Action
	        whereSql:"",//表格查询条件
	        orderSql:"operatingTime",//表格排序条件
	        pkName:"merid",
	        modelName:"org.yingqu.baoli.model.Merchant",//实体全路径
	        tableName:"Merchant",//表名
	        defaultObj:{enabled:"1"},//默认信息，用于表格添加的时候字段默认值
	        isChildren:false,//是否子功能
	        children:[{//子功能的配置
	        	funCode:"merchantitem_main"	        	
	        }],
	        //子功能信息
	        childFun:[],
	        parentCode:"merchant_main",//主功能功能编码
	        connectFields:[{//关联字段
			mainFieldCode:"",//主功能字段名
			childFieldCode:"",//子功能字段名
			foreignKey:"foreignKey",//外键虚字段
			isQuery:true
			}]
	},
		items:[{
		xtype:"basecenterpanel",
				items:[{
					xtype:"basequerypanel",
					region:"north",
					items:[
			  {
				xtype:"basequeryfield",
				queryType:"textfield",
				fieldLabel:"商户名称",
				name:"name",
				config:{
				}
			},
			  {
				xtype:"basequeryfield",
				queryType:"basecombobox",
				fieldLabel:"是否上门",
				name:"come",
				config:{
					ddCode:"ISCOME"
				}
			},
			]
			},{
			xtype:"bl.merchantGrid",
			region:"center"
		}]
	},{
	xtype:"bl.merchantForm",
		hidden:true
	}]
});
