Ext.define("core.bl.inc.view.PhotographPanel",{
	extend:"core.app.base.BasePanel",
	alias:"widget.bl.photographPanel",
	funCode:"photograph_main",
	funData:{
	        action:"/bl/incimg", //请求Action
	        whereSql:"",//表格查询条件
	        orderSql:"operatingTime",//表格排序条件
	        pkName:"iimgid",
	        modelName:"org.yingqu.baoli.model.Photograph",//实体全路径
	        tableName:"Photograph",//表名
	        isChildren:true,//是否子功能
	        parentCode:"interact_main",//主功能功能编码
	        connectFields:[{//关联字段
			mainFieldCode:"interid",//主功能字段名
			childFieldCode:"inter",//子功能字段名
			foreignKey:"foreignKey",//外键虚字段
			isQuery:true
			}]
	},
		items:{
			xtype:"bl.photographGrid",
			region:"center"
		}
});
